# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wolverineks
email: wolverine.ks+blog@gmail.com
description: web developer, musician, person
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wolverineks.github.io" # the base hostname & protocol for your site
twitter_username: wolverine.ks
github_username:  wolverineks

# Build settings
markdown: kramdown

# Added by wolv to fix jekyll bug with excerpts
# https://github.com/jekyll/jekyll/issues/4564
excerpt_separator: ""
